package game;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author İbrahim
 */
public class Game extends javax.swing.JFrame {
    
    public static Game ThisGame;

    // butonları dizilerde tutuyorum
    ArrayList<ArrayList<JButton>> allbuttons;
    ArrayList<JButton> base0;
    ArrayList<JButton> base1;
    ArrayList<JButton> base2;
    ArrayList<JButton> base3;
    ArrayList<JButton> base4;
    ArrayList<JButton> base5;
    ArrayList<JButton> base6;
    ArrayList<JButton> base7;

    boolean gameStarted = false;

    private int kalanHamleSayisi = 60;

    Player player1, player2, currentPlayer, nextPlayer;

    ArrayList<String> beyazTaslar = new ArrayList<>();
    ArrayList<String> siyahTaslar = new ArrayList<>();

    Color defaultcolor = new Color(66, 244, 140);

    private int whiteCount = 2;
    private int blackCount = 2;

    // sol, sol-yukarı, yukarı, sag-yukarı, .... , sol-asagı
    String[] islemler = {"-,0", "-,+", "0,+", "+,+", "+,0", "+,-", "0,-", "-,-"};

    /**
     * Creates new form Game
     */
    public Game() {
        JButton initialButtons;
        initComponents();

        // Paneldeki tüm butonlara aynı eventi atıyorum
        for (Component component : jPanel1.getComponents()) {
            component.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    oyna(evt);
                }
            });
            component.setBackground(defaultcolor);
            initialButtons = (JButton) component;
            initialButtons.setText("");
        }

        allbuttons = new ArrayList<>();
        base0 = new ArrayList<>();
        base1 = new ArrayList<>();
        base2 = new ArrayList<>();
        base3 = new ArrayList<>();
        base4 = new ArrayList<>();
        base5 = new ArrayList<>();
        base6 = new ArrayList<>();
        base7 = new ArrayList<>();

        Collections.addAll(base0, btn_00, btn_01, btn_02, btn_03, btn_04, btn_05, btn_06, btn_07);
        allbuttons.add(base0);

        Collections.addAll(base1, btn_10, btn_11, btn_12, btn_13, btn_14, btn_15, btn_16, btn_17);
        allbuttons.add(base1);

        Collections.addAll(base2, btn_20, btn_21, btn_22, btn_23, btn_24, btn_25, btn_26, btn_27);
        allbuttons.add(base2);

        Collections.addAll(base3, btn_30, btn_31, btn_32, btn_33, btn_34, btn_35, btn_36, btn_37);
        allbuttons.add(base3);

        Collections.addAll(base4, btn_40, btn_41, btn_42, btn_43, btn_44, btn_45, btn_46, btn_47);
        allbuttons.add(base4);

        Collections.addAll(base5, btn_50, btn_51, btn_52, btn_53, btn_54, btn_55, btn_56, btn_57);
        allbuttons.add(base5);

        Collections.addAll(base6, btn_60, btn_61, btn_62, btn_63, btn_64, btn_65, btn_66, btn_67);
        allbuttons.add(base6);

        Collections.addAll(base7, btn_70, btn_71, btn_72, btn_73, btn_74, btn_75, btn_76, btn_77);
        allbuttons.add(base7);

        //allbuttons.get(6).get(2).setBackground(Color.red);        
        allbuttons.get(3).get(4).setBackground(Color.white);
        allbuttons.get(4).get(3).setBackground(Color.white);
        Collections.addAll(beyazTaslar, "3,4", "4,3");

        player1 = new Player("Beyaz", beyazTaslar, Color.white, Color.black);
        currentPlayer = player1;

        allbuttons.get(3).get(3).setBackground(Color.black);
        allbuttons.get(4).get(4).setBackground(Color.black);
        Collections.addAll(siyahTaslar, "3,3", "4,4");

        player2 = new Player("Siyah", siyahTaslar, Color.black, Color.white);
        nextPlayer = player2;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_24 = new javax.swing.JButton();
        btn_14 = new javax.swing.JButton();
        btn_04 = new javax.swing.JButton();
        btn_73 = new javax.swing.JButton();
        btn_63 = new javax.swing.JButton();
        btn_53 = new javax.swing.JButton();
        btn_43 = new javax.swing.JButton();
        btn_33 = new javax.swing.JButton();
        btn_23 = new javax.swing.JButton();
        btn_13 = new javax.swing.JButton();
        btn_03 = new javax.swing.JButton();
        btn_20 = new javax.swing.JButton();
        btn_72 = new javax.swing.JButton();
        btn_10 = new javax.swing.JButton();
        btn_62 = new javax.swing.JButton();
        btn_00 = new javax.swing.JButton();
        btn_47 = new javax.swing.JButton();
        btn_27 = new javax.swing.JButton();
        btn_07 = new javax.swing.JButton();
        btn_17 = new javax.swing.JButton();
        btn_77 = new javax.swing.JButton();
        btn_52 = new javax.swing.JButton();
        btn_42 = new javax.swing.JButton();
        btn_32 = new javax.swing.JButton();
        btn_22 = new javax.swing.JButton();
        btn_37 = new javax.swing.JButton();
        btn_12 = new javax.swing.JButton();
        btn_57 = new javax.swing.JButton();
        btn_02 = new javax.swing.JButton();
        btn_67 = new javax.swing.JButton();
        btn_71 = new javax.swing.JButton();
        btn_76 = new javax.swing.JButton();
        btn_61 = new javax.swing.JButton();
        btn_66 = new javax.swing.JButton();
        btn_51 = new javax.swing.JButton();
        btn_56 = new javax.swing.JButton();
        btn_41 = new javax.swing.JButton();
        btn_46 = new javax.swing.JButton();
        btn_36 = new javax.swing.JButton();
        btn_26 = new javax.swing.JButton();
        btn_16 = new javax.swing.JButton();
        btn_31 = new javax.swing.JButton();
        btn_21 = new javax.swing.JButton();
        btn_11 = new javax.swing.JButton();
        btn_01 = new javax.swing.JButton();
        btn_06 = new javax.swing.JButton();
        btn_70 = new javax.swing.JButton();
        btn_75 = new javax.swing.JButton();
        btn_60 = new javax.swing.JButton();
        btn_65 = new javax.swing.JButton();
        btn_50 = new javax.swing.JButton();
        btn_55 = new javax.swing.JButton();
        btn_40 = new javax.swing.JButton();
        btn_45 = new javax.swing.JButton();
        btn_30 = new javax.swing.JButton();
        btn_35 = new javax.swing.JButton();
        btn_25 = new javax.swing.JButton();
        btn_15 = new javax.swing.JButton();
        btn_05 = new javax.swing.JButton();
        btn_74 = new javax.swing.JButton();
        btn_64 = new javax.swing.JButton();
        btn_54 = new javax.swing.JButton();
        btn_44 = new javax.swing.JButton();
        btn_34 = new javax.swing.JButton();
        lbl_player = new javax.swing.JLabel();
        btn_basla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_24.setText("jButton1");

        btn_14.setText("jButton1");

        btn_04.setText("jButton1");

        btn_73.setText("jButton1");

        btn_63.setText("jButton1");

        btn_53.setText("jButton1");

        btn_43.setText("jButton1");

        btn_33.setText("jButton1");

        btn_23.setText("jButton1");

        btn_13.setText("jButton1");

        btn_03.setText("jButton1");

        btn_20.setText("jButton1");

        btn_72.setText("jButton1");

        btn_10.setText("jButton1");

        btn_62.setText("jButton1");

        btn_00.setText("jButton1");

        btn_47.setText("jButton1");

        btn_27.setText("jButton1");

        btn_07.setText("jButton1");

        btn_17.setText("jButton1");

        btn_77.setText("jButton1");

        btn_52.setText("jButton1");

        btn_42.setText("jButton1");

        btn_32.setText("jButton1");

        btn_22.setText("jButton1");

        btn_37.setText("jButton1");

        btn_12.setText("jButton1");

        btn_57.setText("jButton1");

        btn_02.setText("jButton1");

        btn_67.setText("jButton1");

        btn_71.setText("jButton1");

        btn_76.setText("jButton1");

        btn_61.setText("jButton1");

        btn_66.setText("jButton1");

        btn_51.setText("jButton1");

        btn_56.setText("jButton1");

        btn_41.setText("jButton1");

        btn_46.setText("jButton1");

        btn_36.setText("jButton1");

        btn_26.setText("jButton1");

        btn_16.setText("jButton1");

        btn_31.setText("jButton1");

        btn_21.setText("jButton1");

        btn_11.setText("jButton1");

        btn_01.setText("jButton1");

        btn_06.setText("jButton1");

        btn_70.setText("jButton1");

        btn_75.setText("jButton1");

        btn_60.setText("jButton1");

        btn_65.setText("jButton1");

        btn_50.setText("jButton1");

        btn_55.setText("jButton1");

        btn_40.setText("jButton1");

        btn_45.setText("jButton1");

        btn_30.setText("jButton1");

        btn_35.setText("jButton1");

        btn_25.setText("jButton1");

        btn_15.setText("jButton1");

        btn_05.setText("jButton1");

        btn_74.setText("jButton1");

        btn_64.setText("jButton1");

        btn_54.setText("jButton1");

        btn_44.setText("jButton1");

        btn_34.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_00, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_60, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_70, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_01, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_61, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_71, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_02, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_42, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_52, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_62, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_72, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_03, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_53, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_63, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_73, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_04, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_44, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_54, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_64, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_74, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_05, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_45, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_55, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_65, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_75, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_06, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_56, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_66, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_76, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_07, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_57, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_67, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_77, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_07, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_47, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_57, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_67, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_77, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_06, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_46, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_36, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_56, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_66, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_76, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_05, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_45, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_55, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_65, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_75, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_04, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_44, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_54, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_64, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_74, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_03, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_43, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_53, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_63, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_73, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_02, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_42, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_52, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_62, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_72, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_01, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_41, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_51, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_61, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_71, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_00, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_40, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_50, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_60, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_70, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lbl_player.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_player.setForeground(new java.awt.Color(0, 102, 0));

        btn_basla.setText("Başla");
        btn_basla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baslaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 3, 24)); // NOI18N
        jLabel1.setText("Othello-Riverse");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Oyun Sırası:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lbl_player, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btn_basla, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_player, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(45, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btn_basla)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_baslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baslaActionPerformed

        // Başlangıç durumu
        lbl_player.setText("Beyaz oynuyor..");
        gameStarted = true;
        currentPlayer = player1;
        hamleTahmini();
    }//GEN-LAST:event_btn_baslaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Hangi pozisyonlara taş konulabilir onu belirliyorum.
    private void hamleTahmini() {

        String[] s;
        int x = 0, y = 0;
        for (int i = 0; i < currentPlayer.tasListesi.size(); i++) {
            s = currentPlayer.tasListesi.get(i).split(",");

            x = Integer.parseInt(s[0]);
            y = Integer.parseInt(s[1]);

            System.out.println(x + "," + y);

            taslariGez(x, y, currentPlayer.rivalColor);

        }

    }

    private void taslariGez(int a, int b, Color rivalColor) {
        JButton button;
        boolean rakipGoruldu = false;
        int x, y;
        
        // Her 8 farklı yönü geziyorum
        for (String islem : islemler) {
            switch (islem) {
                case "-,0": 
                    y = b;
                    for (x = (a - 1); x >= 0; x--) {
                        
                        button = allbuttons.get(x).get(y);
                        if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == true) {
                            button.setBackground(Color.red);
                            rakipGoruldu = false;
                        } else if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == false) {
                            continue;
                        } else if (button.getBackground().equals(rivalColor)) {
                            rakipGoruldu = true;
                        }

                    }
                    break;

                case "-,+":
                    for (x = (a - 1); x >= 0; x--) {
                        for (y = (b + 1); y < 8; y++) {
                            button = allbuttons.get(x).get(y);
                            if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == true) {
                                button.setBackground(Color.red);
                                rakipGoruldu = false;
                            } else if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == false) {
                                continue;
                            } else if (button.getBackground().equals(rivalColor)) {
                                rakipGoruldu = true;
                            }
                        }
                    }
                    break;

                case "0,+":
                    x = a;
                    for (y = (b + 1); y < 8; y++) {
                        button = allbuttons.get(x).get(y);
                        if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == true) {
                            button.setBackground(Color.red);
                            rakipGoruldu = false;
                        } else if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == false) {
                            continue;
                        } else if (button.getBackground().equals(rivalColor)) {
                            rakipGoruldu = true;
                        }
                    }

                case "+,+":
                    for (x = (a + 1); x < 8; x++) {
                        for (y = (b + 1); y < 8; y++) {
                            button = allbuttons.get(x).get(y);
                            if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == true) {
                                button.setBackground(Color.red);
                                rakipGoruldu = false;
                            } else if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == false) {
                                continue;
                            } else if (button.getBackground().equals(rivalColor)) {
                                rakipGoruldu = true;
                            }
                        }
                    }
                    break;

                case "+,0":
                    y = b;
                    for (x = (a + 1); x < 8; x++) {
                        button = allbuttons.get(x).get(y);
                        if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == true) {
                            button.setBackground(Color.red);
                            rakipGoruldu = false;
                        } else if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == false) {
                            continue;
                        } else if (button.getBackground().equals(rivalColor)) {
                            rakipGoruldu = true;
                        }
                    }
                    break;

                case "+,-":
                    for (x = (a + 1); x < 8; x++) {
                        for (y = (b - 1); y >= 0; y--) {
                            button = allbuttons.get(x).get(y);
                            if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == true) {
                                button.setBackground(Color.red);
                                rakipGoruldu = false;
                            } else if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == false) {
                                continue;
                            } else if (button.getBackground().equals(rivalColor)) {
                                rakipGoruldu = true;
                            }
                        }
                    }
                    break;

                case "0,-":
                    x = a;
                    for (y = (b - 1); y >= 0; y--) {
                        button = allbuttons.get(x).get(y);
                        if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == true) {
                            button.setBackground(Color.red);
                            rakipGoruldu = false;
                        } else if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == false) {
                            continue;
                        } else if (button.getBackground().equals(rivalColor)) {
                            rakipGoruldu = true;
                        }
                    }
                    break;

                case "-,-":
                    for (x = (a - 1); x >= 0; x--) {
                        for (y = (b - 1); y >= 0; y--) {
                            button = allbuttons.get(x).get(y);
                            if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == true) {
                                button.setBackground(Color.red);
                                rakipGoruldu = false;
                            } else if ((button.getBackground().equals(defaultcolor) || button.getBackground().equals(Color.red)) && rakipGoruldu == false) {
                                continue;
                            } else if (button.getBackground().equals(rivalColor)) {
                                rakipGoruldu = true;
                            }
                        }
                    }
                    break;

                default:
            }
        }
    }
    
    
    private void oyna(MouseEvent evt) {
        JButton clickedButton = (JButton) evt.getSource();
        Player temp;

        String[] s = pozisyonOgren(evt).split(",");

        int x = Integer.valueOf(s[0]);
        int y = Integer.valueOf(s[1]);
        
        // Tıklanan buton rengi kırmızıysa işlem yap
        if (clickedButton.getBackground().equals(Color.red)) {
            clickedButton.setBackground(currentPlayer.ownColor);
            currentPlayer.tasListesi.add(x + "," + y);
            rakipTaslariYe(x, y);
            durumuGuncelle();
            hamleTahmini();

        } else {
              JOptionPane.showMessageDialog(rootPane, "Kırmızı butonlardan birine tıklamalısınız !");
        }

    }

    // Tıklanan pozisyonun sağında solunda vs. yenebilir tüm butonları bir listeye atıyorum
    private void rakipTaslariYe(int a, int b) {
        JButton currentButton;
        int x, y;
        boolean seenOwnColor = false;
        ArrayList<String> buttonsInDirection;

        for (String islem : islemler) {
            switch (islem) {
                case "-,0":
                    buttonsInDirection = new ArrayList<>();
                    y = b;
                    for (x = (a - 1); x >= 0; x--) {
                        currentButton = allbuttons.get(x).get(y);
                        String tasPozisyonu = String.valueOf(x) + "," + String.valueOf(y);
                        if (currentButton.getBackground().equals(defaultcolor) || currentButton.equals(Color.red)) {
                            break;
                        } else if (currentButton.getBackground().equals(currentPlayer.rivalColor)) {
                            buttonsInDirection.add(tasPozisyonu);
                        } else if (currentButton.getBackground().equals(currentPlayer.ownColor)) {
                            yeGitsin(buttonsInDirection);
                            break;
                        }
                    }
                    break;

                case "-,+":
                    buttonsInDirection = new ArrayList<>();
                    for (x = (a - 1); x >= 0; x--) {
                        for (y = (b + 1); y < 8; y++) {
                            currentButton = allbuttons.get(x).get(y);
                            String tasPozisyonu = String.valueOf(x) + "," + String.valueOf(y);
                            if (currentButton.getBackground().equals(defaultcolor) || currentButton.equals(Color.red)) {
                                break;
                            } else if (currentButton.getBackground().equals(currentPlayer.rivalColor)) {
                                buttonsInDirection.add(tasPozisyonu);
                            } else if (currentButton.getBackground().equals(currentPlayer.ownColor)) {
                                yeGitsin(buttonsInDirection);
                                break;
                            }
                        }
                    }
                    break;

                case "0,+":
                    buttonsInDirection = new ArrayList<>();
                    x = a;
                    for (y = (b + 1); y < 8; y++) {
                        currentButton = allbuttons.get(x).get(y);
                        String tasPozisyonu = String.valueOf(x) + "," + String.valueOf(y);
                        if (currentButton.getBackground().equals(defaultcolor) || currentButton.equals(Color.red)) {
                            break;
                        } else if (currentButton.getBackground().equals(currentPlayer.rivalColor)) {
                            buttonsInDirection.add(tasPozisyonu);
                        } else if (currentButton.getBackground().equals(currentPlayer.ownColor)) {
                            yeGitsin(buttonsInDirection);
                            break;
                        }
                    }

                case "+,+":
                    buttonsInDirection = new ArrayList<>();
                    for (x = (a + 1); x < 8; x++) {
                        for (y = (b + 1); y < 8; y++) {
                            currentButton = allbuttons.get(x).get(y);
                            String tasPozisyonu = String.valueOf(x) + "," + String.valueOf(y);
                            if (currentButton.getBackground().equals(defaultcolor) || currentButton.equals(Color.red)) {
                                break;
                            } else if (currentButton.getBackground().equals(currentPlayer.rivalColor)) {
                                buttonsInDirection.add(tasPozisyonu);
                            } else if (currentButton.getBackground().equals(currentPlayer.ownColor)) {
                                yeGitsin(buttonsInDirection);
                                break;
                            }
                        }
                    }
                    break;

                case "+,0":
                    buttonsInDirection = new ArrayList<>();
                    y = b;
                    for (x = (a + 1); x < 8; x++) {
                        currentButton = allbuttons.get(x).get(y);
                        String tasPozisyonu = String.valueOf(x) + "," + String.valueOf(y);
                        if (currentButton.getBackground().equals(defaultcolor) || currentButton.equals(Color.red)) {
                            break;
                        } else if (currentButton.getBackground().equals(currentPlayer.rivalColor)) {
                            buttonsInDirection.add(tasPozisyonu);
                        } else if (currentButton.getBackground().equals(currentPlayer.ownColor)) {
                            yeGitsin(buttonsInDirection);
                            break;
                        }
                    }
                    break;

                case "+,-":
                    buttonsInDirection = new ArrayList<>();
                    for (x = (a + 1); x < 8; x++) {
                        for (y = (b - 1); y >= 0; y--) {
                            currentButton = allbuttons.get(x).get(y);
                            String tasPozisyonu = String.valueOf(x) + "," + String.valueOf(y);
                            if (currentButton.getBackground().equals(defaultcolor) || currentButton.equals(Color.red)) {
                                break;
                            } else if (currentButton.getBackground().equals(currentPlayer.rivalColor)) {
                                buttonsInDirection.add(tasPozisyonu);
                            } else if (currentButton.getBackground().equals(currentPlayer.ownColor)) {
                                yeGitsin(buttonsInDirection);
                                break;
                            }
                        }
                    }
                    break;

                case "0,-":
                    buttonsInDirection = new ArrayList<>();
                    x = a;
                    for (y = (b - 1); y >= 0; y--) {
                        currentButton = allbuttons.get(x).get(y);
                        String tasPozisyonu = String.valueOf(x) + "," + String.valueOf(y);
                        if (currentButton.getBackground().equals(defaultcolor) || currentButton.equals(Color.red)) {
                            break;
                        } else if (currentButton.getBackground().equals(currentPlayer.rivalColor)) {
                            buttonsInDirection.add(tasPozisyonu);
                        } else if (currentButton.getBackground().equals(currentPlayer.ownColor)) {
                            yeGitsin(buttonsInDirection);
                            break;
                        }
                    }
                    break;

                case "-,-":
                    buttonsInDirection = new ArrayList<>();
                    for (x = (a - 1); x >= 0; x--) {
                        for (y = (b - 1); y >= 0; y--) {
                            currentButton = allbuttons.get(x).get(y);
                            String tasPozisyonu = String.valueOf(x) + "," + String.valueOf(y);
                            if (currentButton.getBackground().equals(defaultcolor) || currentButton.equals(Color.red)) {
                                break;
                            } else if (currentButton.getBackground().equals(currentPlayer.rivalColor)) {
                                buttonsInDirection.add(tasPozisyonu);
                            } else if (currentButton.getBackground().equals(currentPlayer.ownColor)) {
                                yeGitsin(buttonsInDirection);
                                break;
                            }
                        }
                    }
                    break;

                default:
            }
        }
    }

    // listeye attığım butonların renklerini güncelliyorum
    private void yeGitsin(ArrayList<String> list) {

        int x, y;
        String[] s;

        for (int i = 0; i < list.size(); i++) {

            s = list.get(i).split(",");

            x = Integer.valueOf(s[0]);
            y = Integer.valueOf(s[1]);

            allbuttons.get(x).get(y).setBackground(currentPlayer.ownColor);
            currentPlayer.tasListesi.add(list.get(i));
            nextPlayer.tasListesi.remove(list.get(i));
        }

    }

    // hamle yaptıktan sonra sıra kimdeyse onu güncelliyorum, oyun bitti mi diye kontrol ediyorum.
    private void durumuGuncelle() {
        Player temp;

        temp = nextPlayer;
        nextPlayer = currentPlayer;
        currentPlayer = temp;

        kalanHamleSayisi--;

        if (kalanHamleSayisi == 0) {
            String winner;
            if (currentPlayer.tasListesi.size() > nextPlayer.tasListesi.size()) {
                winner = currentPlayer.name;
            } else {
                winner = nextPlayer.name;
            }
            JOptionPane.showMessageDialog(null,
                    winner,
                    "CONGRATULATIONS",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        if (lbl_player.getText().equalsIgnoreCase("Beyaz oynuyor..")) {
            lbl_player.setText("Siyah oynuyor..");
        } else {
            lbl_player.setText("Beyaz oynuyor..");
        }

        ekraniTemizle();

    }

    private void ekraniTemizle() {
        JButton button;
        for (int i = 0; i < allbuttons.size(); i++) {
            for (int j = 0; j < allbuttons.get(0).size(); j++) {
                button = allbuttons.get(i).get(j);
                if (button.getBackground().equals(Color.red)) {
                    button.setBackground(defaultcolor);
                }
            }
        }
    }

    private String pozisyonOgren(MouseEvent evt) {
        JButton clickedButton = (JButton) evt.getSource();

        for (int i = 0; i < allbuttons.size(); i++) {
            for (int j = 0; j < allbuttons.get(0).size(); j++) {
                if (clickedButton == allbuttons.get(i).get(j)) {
                    return i + "," + j;
                }
            }
        }
        return "";
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_00;
    private javax.swing.JButton btn_01;
    private javax.swing.JButton btn_02;
    private javax.swing.JButton btn_03;
    private javax.swing.JButton btn_04;
    private javax.swing.JButton btn_05;
    private javax.swing.JButton btn_06;
    private javax.swing.JButton btn_07;
    private javax.swing.JButton btn_10;
    private javax.swing.JButton btn_11;
    private javax.swing.JButton btn_12;
    private javax.swing.JButton btn_13;
    private javax.swing.JButton btn_14;
    private javax.swing.JButton btn_15;
    private javax.swing.JButton btn_16;
    private javax.swing.JButton btn_17;
    private javax.swing.JButton btn_20;
    private javax.swing.JButton btn_21;
    private javax.swing.JButton btn_22;
    private javax.swing.JButton btn_23;
    private javax.swing.JButton btn_24;
    private javax.swing.JButton btn_25;
    private javax.swing.JButton btn_26;
    private javax.swing.JButton btn_27;
    private javax.swing.JButton btn_30;
    private javax.swing.JButton btn_31;
    private javax.swing.JButton btn_32;
    private javax.swing.JButton btn_33;
    private javax.swing.JButton btn_34;
    private javax.swing.JButton btn_35;
    private javax.swing.JButton btn_36;
    private javax.swing.JButton btn_37;
    private javax.swing.JButton btn_40;
    private javax.swing.JButton btn_41;
    private javax.swing.JButton btn_42;
    private javax.swing.JButton btn_43;
    private javax.swing.JButton btn_44;
    private javax.swing.JButton btn_45;
    private javax.swing.JButton btn_46;
    private javax.swing.JButton btn_47;
    private javax.swing.JButton btn_50;
    private javax.swing.JButton btn_51;
    private javax.swing.JButton btn_52;
    private javax.swing.JButton btn_53;
    private javax.swing.JButton btn_54;
    private javax.swing.JButton btn_55;
    private javax.swing.JButton btn_56;
    private javax.swing.JButton btn_57;
    private javax.swing.JButton btn_60;
    private javax.swing.JButton btn_61;
    private javax.swing.JButton btn_62;
    private javax.swing.JButton btn_63;
    private javax.swing.JButton btn_64;
    private javax.swing.JButton btn_65;
    private javax.swing.JButton btn_66;
    private javax.swing.JButton btn_67;
    private javax.swing.JButton btn_70;
    private javax.swing.JButton btn_71;
    private javax.swing.JButton btn_72;
    private javax.swing.JButton btn_73;
    private javax.swing.JButton btn_74;
    private javax.swing.JButton btn_75;
    private javax.swing.JButton btn_76;
    private javax.swing.JButton btn_77;
    private javax.swing.JButton btn_basla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_player;
    // End of variables declaration//GEN-END:variables
}
